//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("JModel", "FK_Answer_Question", "Question", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BizService.Question), "Answer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BizService.Answer), true)]
[assembly: EdmRelationshipAttribute("JModel", "FK_Answer_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BizService.User), "Answer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BizService.Answer), true)]
[assembly: EdmRelationshipAttribute("JModel", "FK_Block_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BizService.User), "Block", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BizService.Block), true)]
[assembly: EdmRelationshipAttribute("JModel", "FK_Block_User1", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BizService.User), "Block", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BizService.Block), true)]
[assembly: EdmRelationshipAttribute("JModel", "FK_MessageTb_Group", "Group", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BizService.Group), "MessageTb", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BizService.MessageTb), true)]
[assembly: EdmRelationshipAttribute("JModel", "FK_Question_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BizService.User), "Question", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BizService.Question), true)]
[assembly: EdmRelationshipAttribute("JModel", "FK_UserState_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BizService.User), "UserState", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BizService.UserState), true)]

#endregion

namespace BizService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ModelEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ModelEntities object using the connection string found in the 'ModelEntities' section of the application configuration file.
        /// </summary>
        public ModelEntities() : base("name=ModelEntities", "ModelEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModelEntities object.
        /// </summary>
        public ModelEntities(string connectionString) : base(connectionString, "ModelEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModelEntities object.
        /// </summary>
        public ModelEntities(EntityConnection connection) : base(connection, "ModelEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Answer> Answers
        {
            get
            {
                if ((_Answers == null))
                {
                    _Answers = base.CreateObjectSet<Answer>("Answers");
                }
                return _Answers;
            }
        }
        private ObjectSet<Answer> _Answers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Block> Blocks
        {
            get
            {
                if ((_Blocks == null))
                {
                    _Blocks = base.CreateObjectSet<Block>("Blocks");
                }
                return _Blocks;
            }
        }
        private ObjectSet<Block> _Blocks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Group> Groups
        {
            get
            {
                if ((_Groups == null))
                {
                    _Groups = base.CreateObjectSet<Group>("Groups");
                }
                return _Groups;
            }
        }
        private ObjectSet<Group> _Groups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MessageTb> MessageTbs
        {
            get
            {
                if ((_MessageTbs == null))
                {
                    _MessageTbs = base.CreateObjectSet<MessageTb>("MessageTbs");
                }
                return _MessageTbs;
            }
        }
        private ObjectSet<MessageTb> _MessageTbs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Question> Questions
        {
            get
            {
                if ((_Questions == null))
                {
                    _Questions = base.CreateObjectSet<Question>("Questions");
                }
                return _Questions;
            }
        }
        private ObjectSet<Question> _Questions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserState> UserStates
        {
            get
            {
                if ((_UserStates == null))
                {
                    _UserStates = base.CreateObjectSet<UserState>("UserStates");
                }
                return _UserStates;
            }
        }
        private ObjectSet<UserState> _UserStates;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Answers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAnswers(Answer answer)
        {
            base.AddObject("Answers", answer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Blocks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlocks(Block block)
        {
            base.AddObject("Blocks", block);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Groups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGroups(Group group)
        {
            base.AddObject("Groups", group);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MessageTbs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessageTbs(MessageTb messageTb)
        {
            base.AddObject("MessageTbs", messageTb);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Questions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuestions(Question question)
        {
            base.AddObject("Questions", question);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserStates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserStates(UserState userState)
        {
            base.AddObject("UserStates", userState);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JModel", Name="Answer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Answer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Answer object.
        /// </summary>
        /// <param name="aId">Initial value of the AId property.</param>
        /// <param name="qID">Initial value of the QID property.</param>
        public static Answer CreateAnswer(global::System.Int32 aId, global::System.Int32 qID)
        {
            Answer answer = new Answer();
            answer.AId = aId;
            answer.QID = qID;
            return answer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AId
        {
            get
            {
                return _AId;
            }
            set
            {
                if (_AId != value)
                {
                    OnAIdChanging(value);
                    ReportPropertyChanging("AId");
                    _AId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AId");
                    OnAIdChanged();
                }
            }
        }
        private global::System.Int32 _AId;
        partial void OnAIdChanging(global::System.Int32 value);
        partial void OnAIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UID
        {
            get
            {
                return _UID;
            }
            set
            {
                OnUIDChanging(value);
                ReportPropertyChanging("UID");
                _UID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UID");
                OnUIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UID;
        partial void OnUIDChanging(Nullable<global::System.Int32> value);
        partial void OnUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QID
        {
            get
            {
                return _QID;
            }
            set
            {
                OnQIDChanging(value);
                ReportPropertyChanging("QID");
                _QID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QID");
                OnQIDChanged();
            }
        }
        private global::System.Int32 _QID;
        partial void OnQIDChanging(global::System.Int32 value);
        partial void OnQIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Answer1
        {
            get
            {
                return _Answer1;
            }
            set
            {
                OnAnswer1Changing(value);
                ReportPropertyChanging("Answer1");
                _Answer1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Answer1");
                OnAnswer1Changed();
            }
        }
        private global::System.String _Answer1;
        partial void OnAnswer1Changing(global::System.String value);
        partial void OnAnswer1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Agree
        {
            get
            {
                return _Agree;
            }
            set
            {
                OnAgreeChanging(value);
                ReportPropertyChanging("Agree");
                _Agree = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Agree");
                OnAgreeChanged();
            }
        }
        private Nullable<global::System.Int32> _Agree;
        partial void OnAgreeChanging(Nullable<global::System.Int32> value);
        partial void OnAgreeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                OnDateTimeChanging(value);
                ReportPropertyChanging("DateTime");
                _DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateTime");
                OnDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateTime;
        partial void OnDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnDateTimeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JModel", "FK_Answer_Question", "Question")]
        public Question Question
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("JModel.FK_Answer_Question", "Question").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("JModel.FK_Answer_Question", "Question").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Question> QuestionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("JModel.FK_Answer_Question", "Question");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Question>("JModel.FK_Answer_Question", "Question", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JModel", "FK_Answer_User", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("JModel.FK_Answer_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("JModel.FK_Answer_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("JModel.FK_Answer_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("JModel.FK_Answer_User", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JModel", Name="Block")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Block : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Block object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Block CreateBlock(global::System.Int32 id)
        {
            Block block = new Block();
            block.ID = id;
            return block;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BlockedUId
        {
            get
            {
                return _BlockedUId;
            }
            set
            {
                OnBlockedUIdChanging(value);
                ReportPropertyChanging("BlockedUId");
                _BlockedUId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BlockedUId");
                OnBlockedUIdChanged();
            }
        }
        private Nullable<global::System.Int32> _BlockedUId;
        partial void OnBlockedUIdChanging(Nullable<global::System.Int32> value);
        partial void OnBlockedUIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BlockedToUId
        {
            get
            {
                return _BlockedToUId;
            }
            set
            {
                OnBlockedToUIdChanging(value);
                ReportPropertyChanging("BlockedToUId");
                _BlockedToUId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BlockedToUId");
                OnBlockedToUIdChanged();
            }
        }
        private Nullable<global::System.Int32> _BlockedToUId;
        partial void OnBlockedToUIdChanging(Nullable<global::System.Int32> value);
        partial void OnBlockedToUIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                OnDateTimeChanging(value);
                ReportPropertyChanging("DateTime");
                _DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateTime");
                OnDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateTime;
        partial void OnDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnDateTimeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JModel", "FK_Block_User", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("JModel.FK_Block_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("JModel.FK_Block_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("JModel.FK_Block_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("JModel.FK_Block_User", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JModel", "FK_Block_User1", "User")]
        public User User1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("JModel.FK_Block_User1", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("JModel.FK_Block_User1", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> User1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("JModel.FK_Block_User1", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("JModel.FK_Block_User1", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JModel", Name="Group")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Group : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Group object.
        /// </summary>
        /// <param name="gId">Initial value of the GId property.</param>
        public static Group CreateGroup(global::System.Int32 gId)
        {
            Group group = new Group();
            group.GId = gId;
            return group;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GId
        {
            get
            {
                return _GId;
            }
            set
            {
                if (_GId != value)
                {
                    OnGIdChanging(value);
                    ReportPropertyChanging("GId");
                    _GId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GId");
                    OnGIdChanged();
                }
            }
        }
        private global::System.Int32 _GId;
        partial void OnGIdChanging(global::System.Int32 value);
        partial void OnGIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GName
        {
            get
            {
                return _GName;
            }
            set
            {
                OnGNameChanging(value);
                ReportPropertyChanging("GName");
                _GName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GName");
                OnGNameChanged();
            }
        }
        private global::System.String _GName;
        partial void OnGNameChanging(global::System.String value);
        partial void OnGNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                OnDateTimeChanging(value);
                ReportPropertyChanging("DateTime");
                _DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateTime");
                OnDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateTime;
        partial void OnDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnDateTimeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JModel", "FK_MessageTb_Group", "MessageTb")]
        public EntityCollection<MessageTb> MessageTbs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MessageTb>("JModel.FK_MessageTb_Group", "MessageTb");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MessageTb>("JModel.FK_MessageTb_Group", "MessageTb", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JModel", Name="MessageTb")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MessageTb : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MessageTb object.
        /// </summary>
        /// <param name="mID">Initial value of the MID property.</param>
        /// <param name="dateTime">Initial value of the DateTime property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        /// <param name="delivered">Initial value of the Delivered property.</param>
        public static MessageTb CreateMessageTb(global::System.Int32 mID, global::System.DateTime dateTime, global::System.String message, global::System.Boolean delivered)
        {
            MessageTb messageTb = new MessageTb();
            messageTb.MID = mID;
            messageTb.DateTime = dateTime;
            messageTb.Message = message;
            messageTb.Delivered = delivered;
            return messageTb;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MID
        {
            get
            {
                return _MID;
            }
            set
            {
                if (_MID != value)
                {
                    OnMIDChanging(value);
                    ReportPropertyChanging("MID");
                    _MID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MID");
                    OnMIDChanged();
                }
            }
        }
        private global::System.Int32 _MID;
        partial void OnMIDChanging(global::System.Int32 value);
        partial void OnMIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GID
        {
            get
            {
                return _GID;
            }
            set
            {
                OnGIDChanging(value);
                ReportPropertyChanging("GID");
                _GID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GID");
                OnGIDChanged();
            }
        }
        private Nullable<global::System.Int32> _GID;
        partial void OnGIDChanging(Nullable<global::System.Int32> value);
        partial void OnGIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FromIP
        {
            get
            {
                return _FromIP;
            }
            set
            {
                OnFromIPChanging(value);
                ReportPropertyChanging("FromIP");
                _FromIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FromIP");
                OnFromIPChanged();
            }
        }
        private global::System.String _FromIP;
        partial void OnFromIPChanging(global::System.String value);
        partial void OnFromIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ToIP
        {
            get
            {
                return _ToIP;
            }
            set
            {
                OnToIPChanging(value);
                ReportPropertyChanging("ToIP");
                _ToIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ToIP");
                OnToIPChanged();
            }
        }
        private global::System.String _ToIP;
        partial void OnToIPChanging(global::System.String value);
        partial void OnToIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                OnDateTimeChanging(value);
                ReportPropertyChanging("DateTime");
                _DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateTime");
                OnDateTimeChanged();
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MessageType
        {
            get
            {
                return _MessageType;
            }
            set
            {
                OnMessageTypeChanging(value);
                ReportPropertyChanging("MessageType");
                _MessageType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MessageType");
                OnMessageTypeChanged();
            }
        }
        private global::System.String _MessageType;
        partial void OnMessageTypeChanging(global::System.String value);
        partial void OnMessageTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Delivered
        {
            get
            {
                return _Delivered;
            }
            set
            {
                OnDeliveredChanging(value);
                ReportPropertyChanging("Delivered");
                _Delivered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Delivered");
                OnDeliveredChanged();
            }
        }
        private global::System.Boolean _Delivered;
        partial void OnDeliveredChanging(global::System.Boolean value);
        partial void OnDeliveredChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JModel", "FK_MessageTb_Group", "Group")]
        public Group Group
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Group>("JModel.FK_MessageTb_Group", "Group").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Group>("JModel.FK_MessageTb_Group", "Group").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Group> GroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Group>("JModel.FK_MessageTb_Group", "Group");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Group>("JModel.FK_MessageTb_Group", "Group", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JModel", Name="Question")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Question : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Question object.
        /// </summary>
        /// <param name="qID">Initial value of the QID property.</param>
        public static Question CreateQuestion(global::System.Int32 qID)
        {
            Question question = new Question();
            question.QID = qID;
            return question;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QID
        {
            get
            {
                return _QID;
            }
            set
            {
                if (_QID != value)
                {
                    OnQIDChanging(value);
                    ReportPropertyChanging("QID");
                    _QID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("QID");
                    OnQIDChanged();
                }
            }
        }
        private global::System.Int32 _QID;
        partial void OnQIDChanging(global::System.Int32 value);
        partial void OnQIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Question1
        {
            get
            {
                return _Question1;
            }
            set
            {
                OnQuestion1Changing(value);
                ReportPropertyChanging("Question1");
                _Question1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Question1");
                OnQuestion1Changed();
            }
        }
        private global::System.String _Question1;
        partial void OnQuestion1Changing(global::System.String value);
        partial void OnQuestion1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UID
        {
            get
            {
                return _UID;
            }
            set
            {
                OnUIDChanging(value);
                ReportPropertyChanging("UID");
                _UID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UID");
                OnUIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UID;
        partial void OnUIDChanging(Nullable<global::System.Int32> value);
        partial void OnUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                OnDateTimeChanging(value);
                ReportPropertyChanging("DateTime");
                _DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateTime");
                OnDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateTime;
        partial void OnDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnDateTimeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JModel", "FK_Answer_Question", "Answer")]
        public EntityCollection<Answer> Answers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Answer>("JModel.FK_Answer_Question", "Answer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Answer>("JModel.FK_Answer_Question", "Answer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JModel", "FK_Question_User", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("JModel.FK_Question_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("JModel.FK_Question_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("JModel.FK_Question_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("JModel.FK_Question_User", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="uId">Initial value of the UId property.</param>
        /// <param name="lastLogin">Initial value of the LastLogin property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static User CreateUser(global::System.Int32 uId, global::System.DateTime lastLogin, global::System.Boolean isActive)
        {
            User user = new User();
            user.UId = uId;
            user.LastLogin = lastLogin;
            user.IsActive = isActive;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UId
        {
            get
            {
                return _UId;
            }
            set
            {
                if (_UId != value)
                {
                    OnUIdChanging(value);
                    ReportPropertyChanging("UId");
                    _UId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UId");
                    OnUIdChanged();
                }
            }
        }
        private global::System.Int32 _UId;
        partial void OnUIdChanging(global::System.Int32 value);
        partial void OnUIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UName
        {
            get
            {
                return _UName;
            }
            set
            {
                OnUNameChanging(value);
                ReportPropertyChanging("UName");
                _UName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UName");
                OnUNameChanged();
            }
        }
        private global::System.String _UName;
        partial void OnUNameChanging(global::System.String value);
        partial void OnUNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IP
        {
            get
            {
                return _IP;
            }
            set
            {
                OnIPChanging(value);
                ReportPropertyChanging("IP");
                _IP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IP");
                OnIPChanged();
            }
        }
        private global::System.String _IP;
        partial void OnIPChanging(global::System.String value);
        partial void OnIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Model
        {
            get
            {
                return _Model;
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.String _Model;
        partial void OnModelChanging(global::System.String value);
        partial void OnModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastLogin
        {
            get
            {
                return _LastLogin;
            }
            set
            {
                OnLastLoginChanging(value);
                ReportPropertyChanging("LastLogin");
                _LastLogin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLogin");
                OnLastLoginChanged();
            }
        }
        private global::System.DateTime _LastLogin;
        partial void OnLastLoginChanging(global::System.DateTime value);
        partial void OnLastLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Datetime
        {
            get
            {
                return _Datetime;
            }
            set
            {
                OnDatetimeChanging(value);
                ReportPropertyChanging("Datetime");
                _Datetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Datetime");
                OnDatetimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Datetime;
        partial void OnDatetimeChanging(Nullable<global::System.DateTime> value);
        partial void OnDatetimeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JModel", "FK_Answer_User", "Answer")]
        public EntityCollection<Answer> Answers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Answer>("JModel.FK_Answer_User", "Answer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Answer>("JModel.FK_Answer_User", "Answer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JModel", "FK_Block_User", "Block")]
        public EntityCollection<Block> Blocks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Block>("JModel.FK_Block_User", "Block");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Block>("JModel.FK_Block_User", "Block", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JModel", "FK_Block_User1", "Block")]
        public EntityCollection<Block> Blocks1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Block>("JModel.FK_Block_User1", "Block");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Block>("JModel.FK_Block_User1", "Block", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JModel", "FK_Question_User", "Question")]
        public EntityCollection<Question> Questions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Question>("JModel.FK_Question_User", "Question");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Question>("JModel.FK_Question_User", "Question", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JModel", "FK_UserState_User", "UserState")]
        public EntityCollection<UserState> UserStates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserState>("JModel.FK_UserState_User", "UserState");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserState>("JModel.FK_UserState_User", "UserState", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="JModel", Name="UserState")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserState : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserState object.
        /// </summary>
        /// <param name="sID">Initial value of the SID property.</param>
        public static UserState CreateUserState(global::System.Int32 sID)
        {
            UserState userState = new UserState();
            userState.SID = sID;
            return userState;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SID
        {
            get
            {
                return _SID;
            }
            set
            {
                if (_SID != value)
                {
                    OnSIDChanging(value);
                    ReportPropertyChanging("SID");
                    _SID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SID");
                    OnSIDChanged();
                }
            }
        }
        private global::System.Int32 _SID;
        partial void OnSIDChanging(global::System.Int32 value);
        partial void OnSIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UID
        {
            get
            {
                return _UID;
            }
            set
            {
                OnUIDChanging(value);
                ReportPropertyChanging("UID");
                _UID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UID");
                OnUIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UID;
        partial void OnUIDChanging(Nullable<global::System.Int32> value);
        partial void OnUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Datetime
        {
            get
            {
                return _Datetime;
            }
            set
            {
                OnDatetimeChanging(value);
                ReportPropertyChanging("Datetime");
                _Datetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Datetime");
                OnDatetimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Datetime;
        partial void OnDatetimeChanging(Nullable<global::System.DateTime> value);
        partial void OnDatetimeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("JModel", "FK_UserState_User", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("JModel.FK_UserState_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("JModel.FK_UserState_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("JModel.FK_UserState_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("JModel.FK_UserState_User", "User", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
